[package]
name = "chrono"
version = "0.4.7"
authors = [
    "Kang Seonghoon <public+rust@mearie.org>",
    "Brandon W Maister <quodlibetor@gmail.com>",
]

description = "Date and time library for Rust"
homepage = "https://github.com/chronotope/chrono"
documentation = "https://docs.rs/chrono/"
repository = "https://github.com/chronotope/chrono"
keywords = ["date", "time", "calendar"]
categories = ["date-and-time"]
readme = "README.md"
license = "MIT/Apache-2.0"
exclude = ["/ci/*", "/.travis.yml", "/appveyor.yml", "/Makefile", "/sgx/*"]

[badges]
travis-ci = { repository = "chronotope/chrono" }
appveyor = { repository = "chronotope/chrono" }

[lib]
name = "chrono"

[features]
default = ["mesalock_sgx"]
clock = ["time"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
time = { version = "0.1.39", optional = true }
num-integer = { git = "https://github.com/crypto-com/sgx-vendor" }
num-traits = { git = "https://github.com/crypto-com/sgx-vendor" }
rustc-serialize = { version = "0.3.20", optional = true }
serde = { version = "1", git = "https://github.com/crypto-com/sgx-vendor", optional = true }
sgx_tstd = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true }

[dev-dependencies]
serde_json = { version = "1" }
serde_derive = { version = "1" }
bincode = { version = "0.8.0" }
num-iter = { version = "0.1.35", default-features = false }
doc-comment = "0.3"

[package.metadata.docs.rs]
all-features = true

[package.metadata.playground]
all-features = true
