[package]
authors = ["Baidu"]
name = "sgx_types"
version = "1.0.9"
repository = "https://github.com/baidu/rust-sgx-sdk"
license-file = "LICENSE"
documentation = "https://dingelish.github.io/"
description = "Rust SGX SDK provides the ability to write Intel SGX applications in Rust Programming Language."
edition = "2018"

[lib]
name = "sgx_types"

[features]
default = []

[dependencies]
