[package]
name = "base64"
version = "0.10.1"
authors = ["Alice Maz <alice@alicemaz.com>", "Marshall Pierce <marshall@mpierce.org>"]
description = "encodes and decodes base64 as bytes or utf8"
repository = "https://github.com/marshallpierce/rust-base64"
documentation = "https://docs.rs/base64"
readme = "README.md"
keywords = ["base64", "utf8", "encode", "decode", "no_std"]
categories = ["encoding"]
license = "MIT/Apache-2.0"
edition = "2018"
exclude = ["/sgx/*"]

[[bench]]
name = "benchmarks"
harness = false

[features]
default = ["std", "mesalock_sgx"]
std = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd", "std"]
alloc = []

[dependencies]
sgx_tstd = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true }

[dev-dependencies]
#criterion = "0.3"
#rand = "0.6.1"
#doc-comment = "0.3"

[profile.bench]
# Useful for better disassembly when using `perf record` and `perf annotate`
debug = true
